mariadb <<SQL
CREATE DATABASE IF NOT EXISTS vm_doc
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'vm_doc'@'127.0.0.1'
  IDENTIFIED BY '${DB_PASS}';

ALTER USER 'vm_doc'@'127.0.0.1'
  IDENTIFIED BY '${DB_PASS}';

GRANT SELECT, INSERT, UPDATE, DELETE,
      CREATE, ALTER, INDEX, REFERENCES
ON vm_doc.*
TO 'vm_doc'@'127.0.0.1';

FLUSH PRIVILEGES;
SQL
